// Code generated by "stringer -type DataType"; DO NOT EDIT.

package dsl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ID-0]
	_ = x[CHAR-1]
	_ = x[VARCHAR-2]
	_ = x[BINARY-3]
	_ = x[VARBINARY-4]
	_ = x[TEXT-5]
	_ = x[BOOL-6]
	_ = x[INT-7]
	_ = x[SERIAL-8]
	_ = x[BIGINT-9]
	_ = x[FLOAT-10]
	_ = x[DATE-11]
	_ = x[DATETIME-12]
}

const _DataType_name = "IDCHARVARCHARBINARYVARBINARYTEXTBOOLINTSERIALBIGINTFLOATDATEDATETIME"

var _DataType_index = [...]uint8{0, 2, 6, 13, 19, 28, 32, 36, 39, 45, 51, 56, 60, 68}

func (i DataType) String() string {
	if i < 0 || i >= DataType(len(_DataType_index)-1) {
		return "DataType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DataType_name[_DataType_index[i]:_DataType_index[i+1]]
}
